# Generated by Django 3.2.12 on 2024-06-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_proPermissionData'),
    ]

    operations = [
        migrations.CreateModel(
            name='proRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('technicalName', models.CharField(default='', max_length=70)),
                ('accessRoles', models.JSONField(blank=True, default=dict, null=True)),
                ('permissionID', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
    ]
