# Generated by Django 3.2.12 on 2024-06-22 13:00

from django.db import migrations

def proRolesData(apps, schema_editor):
    proRoles = apps.get_model('engine', 'proRoles')
    proPermission = apps.get_model('engine', 'proPermission')

    read = proPermission.objects.get(permission='read')
    write = proPermission.objects.get(permission='write')

    roles = [
        {'role': 'superAdmin', 'accessRoles': [2, 3, 4, 5], 'permissionID': [read.id, write.id], 'snippet': 'Super Admin'},
        {'role': 'admin', 'accessRoles': [3, 4, 5], 'permissionID': [read.id, write.id], 'snippet': 'Admin'},
        {'role': 'manager', 'accessRoles': [4, 5], 'permissionID': [read.id, write.id], 'snippet': 'Manager'},
        {'role': 'employee', 'accessRoles': [], 'permissionID': [read.id, write.id], 'snippet': 'Employee'},
        {'role': 'guest', 'accessRoles': [], 'permissionID': [read.id], 'snippet': 'Guest'},
    ]

    for role_data in roles:
        proRoles.objects.create(**role_data)

class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_proRoles'),
    ]

    operations = [
        migrations.RunPython(proRolesData),
    ]
