# Generated by Django 3.2.12 on 2024-06-28 08:44

from django.db import migrations

def proRolesData(apps, schema_editor):
    proRoles = apps.get_model('engine', 'proRoles')
    proPermission = apps.get_model('engine', 'proPermission')

    read = proPermission.objects.get(permission='read')
    write = proPermission.objects.get(permission='write')

    roles = [
        {'name': 'Super Admin', 'technicalName': 'superAdmin', 'accessRoles': [2, 3, 4, 5], 'permissionID': [read.id, write.id]},
        {'name': 'Admin', 'technicalName': 'admin', 'accessRoles': [3, 4, 5], 'permissionID': [read.id, write.id]},
        {'name': 'Manager', 'technicalName': 'manager', 'accessRoles': [4, 5], 'permissionID': [read.id, write.id]},
        {'name': 'Employee', 'technicalName': 'employee', 'accessRoles': [], 'permissionID': [read.id, write.id]},
        {'name': 'Client', 'technicalName': 'client', 'accessRoles': [], 'permissionID': [read.id, write.id]},
        {'name': 'Guest', 'technicalName': 'guest', 'accessRoles': [], 'permissionID': [read.id]},
    ]

    for role_data in roles:
        proRoles.objects.create(**role_data)

class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_proRoles'),
    ]

    operations = [
        migrations.RunPython(proRolesData),
    ]
