# Generated by Django 3.2.12 on 2024-06-28 09:03

from django.db import migrations
from django.utils import timezone
from django.contrib.auth.hashers import make_password

def proUsersData(apps, schema_editor):
    proUsers = apps.get_model('engine', 'proUsers')
    proRoles = apps.get_model('engine', 'proRoles')

    superadmin_role = proRoles.objects.get(technicalName='superAdmin')

    proUsers.objects.create(
        firstName='Admin',
        lastName='Admin',
        email='djangpdev55@gmail.com',
        empID='Admin001',
        userName='admin',
        password=make_password('admin@123'),
        roleID=superadmin_role,
        activate=True,
        sessionActivate=True,
        createdBy=None,
        createdDate=timezone.now()
    )


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_proUsers'),
    ]

    operations = [
        migrations.RunPython(proUsersData),
    ]
