# Generated by Django 3.2.12 on 2024-06-28 09:11

from django.db import migrations

def projectStatusData(apps, schema_editor):
    projectStatus = apps.get_model('engine', 'projectStatus')

    planning = projectStatus.objects.create(
        name='Planning',
        technicalName='planning'
    )

    in_progress = projectStatus.objects.create(
        name='In Progress',
        technicalName='in_progress'
    )

    hold = projectStatus.objects.create(
        name='Hold',
        technicalName='hold'
    )

    completed = projectStatus.objects.create(
        name='Completed',
        technicalName='completed'
    )
    
class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0008_projectStatus'),
    ]

    operations = [
        migrations.RunPython(projectStatusData),
    ]
