# Generated by Django 3.2.12 on 2024-06-22 13:32

from django.db import migrations

def projectTaskStatusData(apps, schema_editor):
    projectTaskStatus = apps.get_model('engine', 'projectTaskStatus')

    Open = projectTaskStatus.objects.create(
        name='Open',
        technicalName='open'
    )

    estimation_required = projectTaskStatus.objects.create(
        name='Estimation Required',
        technicalName='estimation_required'
    )

    analyzation_in_progress = projectTaskStatus.objects.create(
        name='Analyzation In Progress',
        technicalName='analyzation_in_progress'
    )

    in_pm_verifcation = projectTaskStatus.objects.create(
        name='In PM verifcation',
        technicalName='in_pm_verifcation'
    )

    waiting_client_feedBack = projectTaskStatus.objects.create(
        name='Waiting for Client FeedBackn',
        technicalName='waiting_client_feedBack'
    )

    in_progress = projectTaskStatus.objects.create(
        name='In Progress',
        technicalName='in_progress'
    )

    dev_completed = projectTaskStatus.objects.create(
        name='Dev Completed',
        technicalName='dev_completed'
    )

    testing = projectTaskStatus.objects.create(
        name='Testing',
        technicalName='testing'
    )

    bug_fixing = projectTaskStatus.objects.create(
        name='Bug Fixing',
        technicalName='bug_fixing'
    )

    on_hold = projectTaskStatus.objects.create(
        name='on Hold',
        technicalName='on_hold'
    )

    closed = projectTaskStatus.objects.create(
        name='Closed',
        technicalName='closed'
    )

class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0009_projectTaskStatus'),
    ]

    operations = [
        migrations.RunPython(projectTaskStatusData),
    ]
