# Generated by Django 3.2.12 on 2024-06-22 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0011_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(blank=True, null=True)),
                ('clientID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='engine.clients')),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to='engine.prousers')),
                ('projectStatusID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='engine.projectstatus')),
                ('updatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_projects', to='engine.prousers')),
            ],
        ),
    ]
