# Generated by Django 3.2.12 on 2024-06-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0012_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='billingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=70, null=True)),
                ('technicalName', models.CharField(blank=True, default='', max_length=70, null=True)),
            ],
        ),
    ]
