# Generated by Django 3.2.12 on 2024-06-28 09:23

from django.db import migrations

def priorityTypeData(apps, schema_editor):
    priorityType = apps.get_model('engine', 'priorityType')

    none = priorityType.objects.create(
        name='None',
        technicalName='none'
    )

    low = priorityType.objects.create(
        name='Low',
        technicalName='low'
    )

    medium = priorityType.objects.create(
        name='Medium',
        technicalName='medium'
    )

    high = priorityType.objects.create(
        name='High',
        technicalName='high'
    )

class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0014_priorityType'),
    ]

    operations = [
        migrations.RunPython(priorityTypeData),
    ]
