# Generated by Django 3.2.12 on 2024-06-28 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0017_projecttaskgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskNumber', models.CharField(default='', max_length=10)),
                ('taskName', models.CharField(default='', max_length=255)),
                ('taskDescription', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('owners', models.JSONField(blank=True, default=list, null=True)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endlineDate', models.DateField(blank=True, null=True)),
                ('workHours', models.DurationField(blank=True, null=True)),
                ('dueDate', models.DateField(blank=True, null=True)),
                ('taskUniqueID', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(blank=True, null=True)),
                ('billingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.billingtype')),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to='engine.prousers')),
                ('priorityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.prioritytype')),
                ('taskGroupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.projecttaskgroup')),
                ('updatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tasks', to='engine.prousers')),
            ],
        ),
    ]
