# Generated by Django 3.2.12 on 2024-06-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0019_projects_projectnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='taskNumber',
            field=models.CharField(default='', max_length=10),
        ),
    ]
