# Generated by Django 3.2.12 on 2024-06-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0020_projecttask_tasknumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='projectDescription',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
